###
GET http://localhost:4004/browse/triplog?$select=staging_creation_timestamp,fosuffix,indestination,inflightno,inorigin,inscheddeptdate,insupcarriercode2,logtype,status,surrogatenum&$skip=3&$top=80

###
GET http://localhost:4004/browse/triplog?$select=staging_creation_timestamp&$top=3

###
POST http://localhost:4004/browse/triprecord
Content-Type: application/json

{
		"insupcarriercode2": "",
		"inflightno": "",
		"inorigin": "",
		"indestination": "",
		"inscheddeptdate": "1900-01-06",
		"fosuffix": null,
		"surrogatenum": "DanielEmptyTest",
		"aufnr": null,
		"supcarriercode2_code": "AV",
		"scheddeptdate": "2021-01-10",
		"flightno": "0007",
		"supcarriercode_code": "AV",
		"carriercode_code": "AV",
		"origin_code": "FRA",
		"destination_code": "BOG",
		"repeatno": "25",
		"idooutc": "2021-10-14",
		"idoo": "2021-10-14",
		"doo": "2021-10-14",
		"dooutc": "2021-10-14",
		"actarrapt_code": "FRA",
		"actarrapticao": "KFRA",
		"actdeptapt_code": "BOG",
		"actdeptapticao": "SKBO",
		"legstate_code": "RTR",
		"aircrafttype": "330",
		"aircrafttypecpa": null,
		"tailno": "NTT51S",
		"flighttype": "J",
		"deptparkposn": null,
		"actgatetime": 0,
		"servicetype": "P",
		"delayreason1": "99",
		"delayreason2": "99",
		"delayreason3": "99",
		"delayreason4": "99",
		"delayreason5": null,
		"actualflyingdur": 228,
		"scheddepttime": "06:45:00",
		"scheddeptts": 20211013065000,
		"actdeptts": 20211013065000,
		"takeoffdate": "2021-10-14",
		"takeofftime": "06:45:00",
		"touchdndate": "2021-10-14",
		"touchdntime": "06:55:00",
		"actdeptdate": "2021-10-14",
		"actdepttime": "10:43:00",
		"actarrdate": "2021-10-14",
		"actarrtime": "06:50:00",
		"takeoffdateutc": "2021-10-14",
		"takeofftimeutc": "10:48:00",
		"touchdndateutc": "2021-10-14",
		"touchdntimeutc": "11:55:00",
		"actdeptdateutc": "2021-10-14",
		"actdepttimeutc": "10:43:00",
		"actarrdateutc": "2021-10-14",
		"actarrtimeutc": "11:50:00",
		"scheddeptdateutc": "2021-10-14",
		"scheddepttimeutc": "15:35:00",
		"schedarrdateutc": "2021-10-14",
		"schedarrtimeutc": "11:45:00",
		"schedarrdate": "2021-10-14",
		"schedarrtime": "15:30:00",
		"schedarrts": 20211014104000,
		"actarrts": 20211014104000,
		"estdeptdate": "2021-10-14",
		"estdepttime": "10:30:00",
		"estdeptdateutc": null,
		"estdepttimeutc": "00:00:00",
		"estarrdateutc": "2021-10-14",
		"estarrtimeutc": "10:35:00",
		"estarrdate": null,
		"estarrtime": "00:00:00",
		"planblocktime": 225,
		"schedarrapticao": "KFRA",
		"schedarrapt_code": "FRA",
		"scheddeptapticao": "SKBO",
		"scheddeptapt_code": "BOG",
		"flight_tm": 0,
		"arr_stand": null,
		"dep_terminal": null,
		"arr_terminal": null,
		"onblockdate": null,
		"onblocktime": null,
		"offblockdate": null,
		"offblocktime": "00:00:00",
		"taxi_out_time": 5,
		"route": null,
		"cfpno1": "1255",
		"cfpno2": null
	}

###
GET http://localhost:4004/browse/triplog
# GET http://localhost:4004/browse/triplog(insupcarriercode2='',inflightno='',inorigin='',indestination='',inscheddeptdate=1900-01-01,surrogatenum='DanielTest123',logtype='1',creation_timestamp='2022-06-30')

###
POST http://localhost:4004/browse/pax
Content-Type: application/json

{
		"insupcarriercode2": "6",
		"inflightno": "6",
		"inorigin": "6",
		"indestination": "6",
		"inscheddeptdate": "1900-01-06",
		"fosuffix": null,
		"surrogatenum": "DanielTestTS1",
		"version": 70,
        "user_ind": "",
        "firstclasspax": 5,
        "busclasspax": 1,
        "premecopax": 1,
        "ecopax": 2,
        "totalpax": 2,
        "revpaxfirst": 1,
        "revpaxbus": 1,
        "revpaxpreco": 1,
        "revpaxeco": 2,
        "revpaxtot": 2,
        "nrevpaxfirst": 1,
        "nrevpaxbus": 1,
        "nrevpaxpreco": 1,
        "nrevpaxeco": 1,
        "nrevpaxtot": 1,
        "chdpax": 1,
        "infpax": 1,
        "wchpax": 1,
        "wchc": 1,
        "wchs": 1,
        "wchr": 1,
        "wcbd": 1,
        "wcbw": 1,
        "wcmp": 1,
        "wcob": 1,
        "wclb": 1,
        "boardpax": 1,
        "transitpax": 1,
        "transferpax": 1,
        "bagquan": 1,
        "bagweight": 1,
        "traint": 1,
        "tradom": 0,
        "creation_timestamp": 20210525042713,
        "tecnum": 0,
        "cabnum": 0,
        "capnum": 0,
        "cocnum": 0,
        "ecavml": 0,
        "ecbbml": 0,
        "ecblml": 0,
        "ecchml": 0,
        "ecdbml": 0,
        "ecfpml": 0,
        "ecgfml": 0,
        "echnml": 0,
        "ecksml": 0,
        "eclcml": 0,
        "eclfml": 0,
        "eclsml": 0,
        "ecmoml": 0,
        "ecnlml": 0,
        "ecorml": 0,
        "ecrvml": 0,
        "ecsfml": 0,
        "ecvgml": 0,
        "ecvjml": 0,
        "ecvlml": 0,
        "ecvoml": 0,
        "bcavml": 0,
        "bcbbml": 0,
        "bcblml": 0,
        "bcchml": 0,
        "bcdbml": 0,
        "bcfpml": 0,
        "bcgfml": 0,
        "bchnml": 0,
        "bcksml": 0,
        "bclcml": 0,
        "bclfml": 0,
        "bclsml": 0,
        "bcmoml": 0,
        "bcnlml": 0,
        "bcorml": 0,
        "bcrvml": 0,
        "bcsfml": 0,
        "bcvgml": 0,
        "bcvjml": 0,
        "bcvlml": 0,
        "bcvoml": 0
}

###
POST http://localhost:4004/browse/cargorecord
Content-Type: application/json

{
        "insupcarriercode2": "8",
		"inflightno": "8",
		"inorigin": "8",
		"indestination": "8",
		"inscheddeptdate": "1900-01-08",
		"fosuffix": null,
		"surrogatenum": "DanielNavTest6",
        "version": "1",
        "user_ind": "",
        "chgtottonn": 4700.00,
        "acttottonn": 3664.90,
        "tottranstonn": 1832.00,
        "chgtotimptonn": 2112.00,
        "acttotimptonn": 1832.90,
        "chgtotexptonn": 4277.00,
        "acttotexptonn": 3664.90,
        "chgimploose": 0,
        "actimploose": 0,
        "chgimpprepck": 0,
        "actimpprepck": 0,
        "chgexploose": 0,
        "actexploose": 0,
        "chgexpprepack": 0,
        "actexpprepack": 0,
        "chgmailimport": 275.00,
        "actmailimport": 275.00,
        "chgmailexport": 384.00,
        "actmailexport": 384.00,
        "avichgtkg": 0,
        "aviactkg": 0,
        "avinoawb": 0,
        "dgrchgtkg": 17.00,
        "dgractkg": 17.00,
        "dgrnoawb": 1,
        "humchgkg": 0,
        "humactkg": 0,
        "humnoawb": 0,
        "perchgkg": 8.50,
        "peractkg": 7.00,
        "pernoawb": 1,
        "valchgkg": 0,
        "valactkg": 0,
        "valnoawb": 0,
        "pilchgkg": 0,
        "pilactkg": 0,
        "pilnoawb": 0,
        "pefchgkg": 0,
        "pefactkg": 0,
        "pefnoawb": 0,
        "temchgkg": 0,
        "temactkg": 0,
        "temnoawb": 0,
        "vunchgkg": 0,
        "vunactkg": 0,
        "vunnoawb": 0,
        "totawb": 29,
        "chgtransloose": 0,
        "acttransloose": 0,
        "chgtransprepack": 0,
        "acttransprepack": 0,
        "chgephloose": 0,
        "actephloose": 0,
        "chgephprepack": 0,
        "actephprepack": 0,
        "chgepdcgo": 0,
        "actepdcgo": 0,
        "creation_timestamp": 20200617125922,
        "chgimptonn": 0,
        "chgexptonn": 0,
        "chgtottranstonn": 2165.00
    }       