###
GET http://localhost:4004/browse/triplog?$select=staging_creation_timestamp,fosuffix,indestination,inflightno,inorigin,inscheddeptdate,insupcarriercode2,logtype,status,surrogatenum&$skip=3&$top=80

###
GET http://localhost:4004/browse/triplog?$select=staging_creation_timestamp&$top=3

###
GET http://localhost:4004/browse/cockpitTripsActuals?$filter=(zzscheddeptdate gt 2021-10-12)

###
POST http://localhost:4004/browse/triprecord
# POST https://triprecord-triprecordspace-triporder-srv.cfapps.eu10.hana.ondemand.com/browse/triprecord
Content-Type: application/json

{
		"insupcarriercode2": "",
		"inflightno": "",
		"inorigin": "",
		"indestination": "",
		"inscheddeptdate": "1900-01-01",
		"fosuffix": null,
		"surrogatenum": "000001",
		"aufnr": null,
		"supcarriercode2_code": "AV",
        "supcarriercode_code": "AV",
        "carriercode_code": "AV",
        "flightno": "0006",
        "origin_code": "BOG",
        "destination_code": "FRA",
        "repeatno": "21",
        "fosuffix": "-",
        "idooutc": "2022-08-01",
        "idoo": "2022-08-01",
        "doo": "2022-08-01",
        "dooutc": "2022-08-01",
        "actarrapt_code": "FRA",
        "actarrapticao": "KFRA",
        "actdeptapt_code": "BOG",
        "actdeptapticao": "SKBO",
        "legstate_code": "ARE",
        "aircrafttype": "330",
        "aircrafttypecpa": "",
        "tailno": "N280AV",
        "flighttype": "J",
        "deptparkposn": "",
        "actgatetime": 0,
        "servicetype": "P",
        "delayreason1": "99",
        "delayreason2": "99",
        "delayreason3": "99",
        "delayreason4": "99",
        "delayreason5": "",
        "actualflyingdur": 228,
        "scheddeptdate": "2022-08-01",
        "scheddepttime": "06:45:00",
        "takeoffdate": "2022-08-01",
        "takeofftime": "06:55:00",
        "touchdndate": "2022-08-01",
        "touchdntime": "10:43:00",
        "actdeptdate": "2022-08-01",
        "actdepttime": "06:50:00",
        "actarrdate": "2022-08-01",
        "actarrtime": "10:48:00",
        "takeoffdateutc": "2022-08-01",
        "takeofftimeutc": "11:55:00",
        "touchdndateutc": "2022-08-01",
        "touchdntimeutc": "10:43:00",
        "actdeptdateutc": "2022-08-01",
        "actdepttimeutc": "11:50:00",
        "actarrdateutc": "2022-08-01",
        "actarrtimeutc": "15:35:00",
        "scheddeptdateutc": "2022-08-01",
        "scheddepttimeutc": "11:45:00",
        "schedarrdateutc": "2022-08-01",
        "schedarrtimeutc": "15:30:00",
        "schedarrdate": "2022-08-01",
        "schedarrtime": "10:30:00",
        "estdepttime": "00:00:00",
        "estdepttimeutc": "00:00:00",
        "estarrdateutc": "2022-08-01",
        "estarrtimeutc": "10:35:00",
        "estarrtime": "00:00:00",
        "planblocktime": 226,
        "schedarrapticao": "KFRA",
        "schedarrapt_code": "FRA",
        "scheddeptapticao": "SKBO",
        "scheddeptapt_code": "BOG",
        "flight_tm": 0,
        "arr_stand": "",
        "dep_terminal": "1",
        "arr_terminal": "",
        "onblocktime": "00:00:00",
        "offblocktime": "00:00:00",
        "taxi_out_time": 5,
        "route": "",
        "cfpno1": "1255",
        "cfpno2": ""
	}

###
GET http://localhost:4004/browse/triplog
# GET http://localhost:4004/browse/triplog(insupcarriercode2='',inflightno='',inorigin='',indestination='',inscheddeptdate=1900-01-01,surrogatenum='DanielTest123',logtype='1',creation_timestamp='2022-06-30')

###
POST http://localhost:4004/browse/pax
Content-Type: application/json

{
		"insupcarriercode2": "6",
		"inflightno": "6",
		"inorigin": "6",
		"indestination": "6",
		"inscheddeptdate": "1900-01-06",
		"fosuffix": null,
		"surrogatenum": "DanielTestTS1",
		"version": 70,
        "user_ind": "",
        "firstclasspax": 5,
        "busclasspax": 1,
        "premecopax": 1,
        "ecopax": 2,
        "totalpax": 2,
        "revpaxfirst": 1,
        "revpaxbus": 1,
        "revpaxpreco": 1,
        "revpaxeco": 2,
        "revpaxtot": 2,
        "nrevpaxfirst": 1,
        "nrevpaxbus": 1,
        "nrevpaxpreco": 1,
        "nrevpaxeco": 1,
        "nrevpaxtot": 1,
        "chdpax": 1,
        "infpax": 1,
        "wchpax": 1,
        "wchc": 1,
        "wchs": 1,
        "wchr": 1,
        "wcbd": 1,
        "wcbw": 1,
        "wcmp": 1,
        "wcob": 1,
        "wclb": 1,
        "boardpax": 1,
        "transitpax": 1,
        "transferpax": 1,
        "bagquan": 1,
        "bagweight": 1,
        "traint": 1,
        "tradom": 0,
        "creation_timestamp": 20210525042713,
        "tecnum": 0,
        "cabnum": 0,
        "capnum": 0,
        "cocnum": 0,
        "ecavml": 0,
        "ecbbml": 0,
        "ecblml": 0,
        "ecchml": 0,
        "ecdbml": 0,
        "ecfpml": 0,
        "ecgfml": 0,
        "echnml": 0,
        "ecksml": 0,
        "eclcml": 0,
        "eclfml": 0,
        "eclsml": 0,
        "ecmoml": 0,
        "ecnlml": 0,
        "ecorml": 0,
        "ecrvml": 0,
        "ecsfml": 0,
        "ecvgml": 0,
        "ecvjml": 0,
        "ecvlml": 0,
        "ecvoml": 0,
        "bcavml": 0,
        "bcbbml": 0,
        "bcblml": 0,
        "bcchml": 0,
        "bcdbml": 0,
        "bcfpml": 0,
        "bcgfml": 0,
        "bchnml": 0,
        "bcksml": 0,
        "bclcml": 0,
        "bclfml": 0,
        "bclsml": 0,
        "bcmoml": 0,
        "bcnlml": 0,
        "bcorml": 0,
        "bcrvml": 0,
        "bcsfml": 0,
        "bcvgml": 0,
        "bcvjml": 0,
        "bcvlml": 0,
        "bcvoml": 0
}

###
POST http://localhost:4004/browse/cargorecord
Content-Type: application/json

{
        "insupcarriercode2": "8",
		"inflightno": "8",
		"inorigin": "8",
		"indestination": "8",
		"inscheddeptdate": "1900-01-08",
		"fosuffix": null,
		"surrogatenum": "DanielNavTest6",
        "version": "1",
        "user_ind": "",
        "chgtottonn": 4700.00,
        "acttottonn": 3664.90,
        "tottranstonn": 1832.00,
        "chgtotimptonn": 2112.00,
        "acttotimptonn": 1832.90,
        "chgtotexptonn": 4277.00,
        "acttotexptonn": 3664.90,
        "chgimploose": 0,
        "actimploose": 0,
        "chgimpprepck": 0,
        "actimpprepck": 0,
        "chgexploose": 0,
        "actexploose": 0,
        "chgexpprepack": 0,
        "actexpprepack": 0,
        "chgmailimport": 275.00,
        "actmailimport": 275.00,
        "chgmailexport": 384.00,
        "actmailexport": 384.00,
        "avichgtkg": 0,
        "aviactkg": 0,
        "avinoawb": 0,
        "dgrchgtkg": 17.00,
        "dgractkg": 17.00,
        "dgrnoawb": 1,
        "humchgkg": 0,
        "humactkg": 0,
        "humnoawb": 0,
        "perchgkg": 8.50,
        "peractkg": 7.00,
        "pernoawb": 1,
        "valchgkg": 0,
        "valactkg": 0,
        "valnoawb": 0,
        "pilchgkg": 0,
        "pilactkg": 0,
        "pilnoawb": 0,
        "pefchgkg": 0,
        "pefactkg": 0,
        "pefnoawb": 0,
        "temchgkg": 0,
        "temactkg": 0,
        "temnoawb": 0,
        "vunchgkg": 0,
        "vunactkg": 0,
        "vunnoawb": 0,
        "totawb": 29,
        "chgtransloose": 0,
        "acttransloose": 0,
        "chgtransprepack": 0,
        "acttransprepack": 0,
        "chgephloose": 0,
        "actephloose": 0,
        "chgephprepack": 0,
        "actephprepack": 0,
        "chgepdcgo": 0,
        "actepdcgo": 0,
        "creation_timestamp": 20200617125922,
        "chgimptonn": 0,
        "chgexptonn": 0,
        "chgtottranstonn": 2165.00
    }       