###
POST http://localhost:4004/browse/triprecord
Content-Type: application/json

{
		"insupcarriercode2": "",
		"inflightno": "",
		"inorigin": "",
		"indestination": "",
		"inscheddeptdate": "1900-01-01",
		"fosuffix": null,
		"surrogatenum": "DanielTest12",
		"aufnr": null,
		"supcarriercode2_code": "AV",
		"scheddeptdate": "2021-10-18",
		"flightno": "0007",
		"supcarriercode_code": "AV",
		"carriercode_code": "AV",
		"origin_code": "FRA",
		"destination_code": "BOG",
		"repeatno": "25",
		"idooutc": "2021-10-13",
		"idoo": "2021-10-13",
		"doo": "2021-10-13",
		"dooutc": "2021-10-13",
		"actarrapt_code": "FRA",
		"actarrapticao": "KFRA",
		"actdeptapt_code": "BOG",
		"actdeptapticao": "SKBO",
		"legstate_code": "ARR",
		"aircrafttype": "330",
		"aircrafttypecpa": null,
		"tailno": "N280AV",
		"flighttype": "J",
		"deptparkposn": null,
		"actgatetime": 0,
		"servicetype": "P",
		"delayreason1": "99",
		"delayreason2": "99",
		"delayreason3": "99",
		"delayreason4": "99",
		"delayreason5": null,
		"actualflyingdur": 228,
		"scheddepttime": "06:45:00",
		"scheddeptts": 20211013065000,
		"actdeptts": 20211013065000,
		"takeoffdate": "2021-10-13",
		"takeofftime": "06:45:00",
		"touchdndate": "2021-10-13",
		"touchdntime": "06:55:00",
		"actdeptdate": "2021-10-13",
		"actdepttime": "10:43:00",
		"actarrdate": "2021-10-13",
		"actarrtime": "06:50:00",
		"takeoffdateutc": "2021-10-14",
		"takeofftimeutc": "10:48:00",
		"touchdndateutc": "2021-10-13",
		"touchdntimeutc": "11:55:00",
		"actdeptdateutc": "2021-10-14",
		"actdepttimeutc": "10:43:00",
		"actarrdateutc": "2021-10-13",
		"actarrtimeutc": "11:50:00",
		"scheddeptdateutc": "2021-10-14",
		"scheddepttimeutc": "15:35:00",
		"schedarrdateutc": "2021-10-13",
		"schedarrtimeutc": "11:45:00",
		"schedarrdate": "2021-10-14",
		"schedarrtime": "15:30:00",
		"schedarrts": 20211014104000,
		"actarrts": 20211014104000,
		"estdeptdate": "2021-10-14",
		"estdepttime": "10:30:00",
		"estdeptdateutc": null,
		"estdepttimeutc": "00:00:00",
		"estarrdateutc": "2021-10-14",
		"estarrtimeutc": "10:35:00",
		"estarrdate": null,
		"estarrtime": "00:00:00",
		"planblocktime": 225,
		"schedarrapticao": "KFRA",
		"schedarrapt_code": "FRA",
		"scheddeptapticao": "SKBO",
		"scheddeptapt_code": "BOG",
		"flight_tm": 0,
		"arr_stand": null,
		"dep_terminal": null,
		"arr_terminal": null,
		"onblockdate": null,
		"onblocktime": null,
		"offblockdate": null,
		"offblocktime": "00:00:00",
		"taxi_out_time": 5,
		"route": null,
		"cfpno1": "1255",
		"cfpno2": null
	}
